version: '0.0.2'
source: "https://github.com/tr7zw/ProcessedModTemplate/tree/master"
replacements:
  name: "ItemSwapper"
  id: "itemswapper"
  version: "0.7.4"
  description: "Proof of concept mod to for a different system to swap items in the inventory."
  homepageUrl: "https://modrinth.com/plugin/itemswapper"
  sourcesUrl: "https://github.com/tr7zw/ItemSwapper"
  issuesUrl: "https://github.com/tr7zw/ItemSwapper/issues"
  fabric_entrypoint: "dev.tr7zw.itemswapper.ItemSwapperMod"
  fabric_modmenu_entrypoint: "dev.tr7zw.itemswapper.ItemSwapperModMenu"
  relocationpackage: "dev.tr7zw.itemswapper"
  modrinthid: RPOSBQgq
  curseforgeid: 694358
  versionlessname: "XTVersionless"
  fabric_dependencies: "
      modCompileOnlyApi 'maven.modrinth:midnightcontrols:1.9.3+1.20.4'\n
      modCompileOnly 'maven.modrinth:midnightlib:1.0.0-fabric'\n
      modCompileOnly 'org.aperlambda:lambdajcommon:1.8.1'\n
      modCompileOnly 'curse.maven:litematica-308892:4626718'\n
    "
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
  - versionless
rootProject:
  template: "."
subProjects:
  XTVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '